### ISSUE TITLE
Support for Ubuntu 18.04

### ISSUE THREAD

**Issue by amercader** [ckan/ckan-packaging#14]
@kowh-ai Looking at the steps that @Zharktas followed to add support for 16.04 should make this really straightforward: https://github.com/ckan/ckan-packaging/pull/11

The [source install instructions](https://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html) should list any Ubuntu 18.04 specific changes that need to be replicated in the Ansible script (if any).

As part of this, you can review the [package install instructions](https://docs.ckan.org/en/latest/maintaining/installing/install-from-package.html) to see if they need to be updated.

**Comment by Zharktas** [comment]
Package install instructions will fail with solr due to https://github.com/ckan/ckan/issues/4762 though.
