### ISSUE TITLE
Cannot build 2.6.0 using this script

### ISSUE THREAD

**Issue by rwillmer** [ckan/ckan-packaging#9]
2.6.0 is the latest released version, we should be able to build a package for this.

The build script relies on being able to pull a version called "release-v<X.Y.Z>"

The repo does not have a release-v2.6.0 tag, so the build fails.

It looks as though the current practice is to tag each release with "ckan-<X.Y.Z>", so that is what the build should be pulling.

If this is also used for building debs/rpms for works-in-progress, then it might be better to change the build script to be able to cope with either branches or tags?

I'll send you a PR with my fix for this.

**Comment by amercader** [comment]
Many thanks for reporting this @rwillmer, I forgot to push the changes to address this during the last release (https://github.com/ckan/ckan-packaging/pull/10#issuecomment-272887869). Luckily I could find them on my old laptop :)
